version: '3'

services:
  appgo:
    image: golang:1.19
    volumes:
      - ./appgo:/go/src/app
    ports:
      - "8000:8000"
    command: "tail -f /dev/null"

  mysql: 
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: root
    ports:
     - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql


